os: linux
arch:
 - amd64
 - ppc64le
 
language: erlang

otp_release:
  - "23.0.2"
  - "22.3.4"

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get install erlang
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install telescope

script: "tsc -f specs/*"
